# Generated by Django 5.1.6 on 2025-02-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp of the resource usage log.",
                        help_text="The date and time when the resource usage was recorded.",
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        db_comment="CPU usage percentage.",
                        help_text="Percentage of CPU usage at the time of logging.",
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        db_comment="Memory (RAM) usage percentage.",
                        help_text="Percentage of RAM usage at the time of logging.",
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        db_comment="Disk usage percentage.",
                        help_text="Percentage of disk space used at the time of logging.",
                    ),
                ),
                (
                    "network_sent",
                    models.FloatField(
                        db_comment="Network data sent in megabytes (MB).",
                        help_text="Amount of data sent over the network (in MB).",
                    ),
                ),
                (
                    "network_received",
                    models.FloatField(
                        db_comment="Network data received in megabytes (MB).",
                        help_text="Amount of data received over the network (in MB).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Usage",
                "verbose_name_plural": "Resource Usages",
                "ordering": ["-timestamp"],
            },
        ),
    ]
