# Generated by Django 5.1.6 on 2025-02-20 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourceusage",
            options={
                "ordering": ["-to_time"],
                "verbose_name": "Resource Usage",
                "verbose_name_plural": "Resource Usages",
            },
        ),
        migrations.RemoveField(
            model_name="resourceusage",
            name="network_received",
        ),
        migrations.RemoveField(
            model_name="resourceusage",
            name="network_sent",
        ),
        migrations.RemoveField(
            model_name="resourceusage",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="from_time",
            field=models.DateTimeField(
                blank=True,
                db_comment="Start time of the resource usage period (Optional).",
                help_text="The optional start time of the resource usage monitoring period.",
                null=True,
                verbose_name="Start Time",
            ),
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="to_time",
            field=models.DateTimeField(
                db_comment="End time of the resource usage period or the time when resource usage was recorded.",
                default=django.utils.timezone.now,
                help_text="The end time of the resource usage monitoring period. Defaults to now if not provided.",
                verbose_name="End Time",
            ),
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="total_disk_read",
            field=models.FloatField(
                db_comment="Total disk read in megabytes (MB).",
                default=0,
                help_text="Total amount of data read from the disk (in MB).",
                verbose_name="Total Disk Read",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="total_disk_write",
            field=models.FloatField(
                db_comment="Total disk write in megabytes (MB).",
                default=0,
                help_text="Total amount of data written to the disk (in MB).",
                verbose_name="Total Disk Write",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="total_network_received",
            field=models.FloatField(
                db_comment="Network data received in megabytes (MB).",
                default=0,
                help_text="Amount of data received over the network (in MB).",
                verbose_name="Total Network Received",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="total_network_sent",
            field=models.FloatField(
                db_comment="Network data sent in megabytes (MB).",
                default=0,
                help_text="Amount of data sent over the network (in MB).",
                verbose_name="Total Network Sent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resourceusage",
            name="cpu_usage",
            field=models.FloatField(
                db_comment="CPU usage percentage.",
                help_text="Percentage of CPU usage at the time of logging.",
                verbose_name="CPU Usage",
            ),
        ),
        migrations.AlterField(
            model_name="resourceusage",
            name="disk_usage",
            field=models.FloatField(
                db_comment="Disk usage percentage.",
                help_text="Percentage of disk space used at the time of logging.",
                verbose_name="Disk Usage",
            ),
        ),
        migrations.AlterField(
            model_name="resourceusage",
            name="memory_usage",
            field=models.FloatField(
                db_comment="Memory (RAM) usage percentage.",
                help_text="Percentage of RAM usage at the time of logging.",
                verbose_name="Memory Usage",
            ),
        ),
    ]
